name: Build docker image


permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - master
  create:
    tags:
      - v*

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to ghcr
      uses: docker/login-action@v2 
      with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: docker/build-push-action@v3
      with:
        tags: ${{ github.repository }}, ghcr.io/${{ github.repository }}
        push: true
        context: .
