name: Build docker image


permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - master
  create:
    tags:
      - v*

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: docker/build-push-action@v2
      with:
        tags: zekker6/latex,ghcr.io/zekker6/latex
        tag_with_ref: true
        tag_with_sha: true
        dockerfile: Dockerfile
